/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author Lucas & Filip
 */
public class Menu extends javax.swing.JPanel {
    private Image background;
    private Image logo;
    private JLabel logoLabel;
    private JLabel start;
    private JButton buttonStart;
    Application parent;
    /**
     * Creates new form NewJPanel
     */
    public Menu(Application application) {
        this.parent = application;
        ImageIcon iiBackground = new ImageIcon("src/resources/background4.png");
        background = iiBackground.getImage();
        int w = background.getWidth(this);
        int h = background.getHeight(this);
        setPreferredSize(new Dimension(w, h));
        setLayout(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
                
        buttonStart=new JButton();
        buttonStart.setBounds(120,300,130,50);
        buttonStart.setText("Start");
        buttonStart.setFocusPainted(false);
        buttonStart.setForeground(Color.WHITE);
        buttonStart.setBackground(new Color(230, 51, 45));
	buttonStart.setFont(new Font("sansserif",0,12));
        buttonStart.setVisible(true);
        add(buttonStart);
        
        buttonStart.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
			    parent.changeCard();
			}
		});
        
        start=new JLabel();
        start.setBounds(120,330,130,50);
        start.setText("press start to continue");
        start.setVisible(true);
        add(start);
        
        logoLabel=new JLabel();
        logoLabel.setBounds(-25,0,420, 236);
        ImageIcon iiLogo = new ImageIcon("src/resources/logo.png");
        logo= iiLogo.getImage();
        logoLabel.setIcon(iiLogo);
        logoLabel.setEnabled(true);
        logoLabel.setVisible(true);
        add(logoLabel);
    }
    /**
     * Overwritten to draw the background pictures
     */
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
            g.drawImage(background, 0, 0, null);
    
        
        Toolkit.getDefaultToolkit().sync();
    }

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("pressed");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
